version: '3.8'

services:
  express:
    build:
      context: ./express
    container_name: express_app
    working_dir: /usr/src/app
    volumes:
      - ./express:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  php:
    build:
      context: ./php
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: triad
      MYSQL_DATABASE: booking
      MYSQL_USER: test
      MYSQL_PASSWORD: triad
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
